spring:
  application:
    name: booking

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${MYSQL_USER:test}
    password: ${MYSQL_PASSWORD:test}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100

    open-in-view: false

jwt:
  secret: ${JWT_SECRET:my-secret-key-for-ch-booking-system-web-app-at-least-32-characters}
  access-token-expiry: 180_000 #30분
  refresh-token-expiry: 2_592_000_000 #30일

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json