spring:
  application:
    name: booking
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

jwt:
  access-token-expiry: 1_800_000    # 30분
  refresh-token-expiry: 2_592_000_000  # 30일

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
